name: mysql1
services:
  mysql1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: northwind
    ports:
      - "3306:3306"
    volumes:
      - ./sampledbs:/docker-entrypoint-initdb.d
